feat: add log levels (WIP title)
getsentry/sentry-native pull request #1107
Opened 2024-12-18 11:08 UTC by JoshuaMoelans

Fixes https://github.com/getsentry/sentry-native/issues/888
Related to https://github.com/getsentry/sentry-cocoa/issues/4467

Main goal is to allow to output warnings from `sentry_init` even when debug is set to `false`. To allow for this, we introduce log levels as a way to control what level of output the user wants.

2024-12-18 13:41 UTC, JoshuaMoelans commented on src/sentry_options.c
> +    opts->debug = true;
We implicitly expect that the user wants to have debug output when setting the logger level (hence we call this from `sentry_options_set_debug` as well).

2024-12-18 16:27 UTC, supervacuus requested changes
I expected the macro name change to highlight a few inconsistencies.

A short sync might also be acceptable regarding the options interface.

2024-12-19 12:10 UTC, JoshuaMoelans commented on include/sentry.h
> +
Removed this overcomplication splitting up global and init log levels. Now we just allow setting of the log level globally.

2024-12-19 13:36 UTC, supervacuus commented on CHANGELOG.md
> +- Add `sentry_init` and global logger log levels ([#1107](https://github.com/getsentry/sentry-native/pull/1107))
```suggestion
**Features**:

- Add option to set debug log level. ([#1107](https://github.com/getsentry/sentry-native/pull/1107))
```

2024-12-19 13:36 UTC, supervacuus approved these changes

2024-12-19 14:27 UTC, merged