build: Use the correct output directory for Makefile target
getsentry/sentry-native pull request #359
Opened 2020-08-25 11:59 UTC by Swatinem

2020-08-25 14:13 UTC, flub approved these changes

2020-08-26 07:48 UTC, jan-auer requested changes
Can we instead set the binary directory of the crashpad `add_subdirectory` according to [the documentation](https://cmake.org/cmake/help/latest/command/add_subdirectory.html), and then also fix the crashpad CMake files instead? 

This approach is not as nice, as it forces everyone importing the CMake project to make the same adjustments. We can do this for the leak-build, as that is an internal test, but better not for a public asset.

2020-08-26 07:51 UTC, Swatinem commented
As I wrote in chat, the contents and paths of the build directory are intermediate assets and the build system can put them wherever it sees fit. The only real guarantee that we have is if we actually use the `install` target I think.

2020-08-26 07:53 UTC, jan-auer commented
I disagree with that, as the `binary_dir` argument is clearly meant for placing final outputs in a certain location. If you really prefer to keep the current structure, however, then let's instead work on the `install` target. Either way, the current patch is insufficient.

2021-04-16 12:34 UTC, closed without merging