fix: Use a u32 value for the signum on Windows
getsentry/sentry-native pull request #385
Opened 2020-10-01 10:36 UTC by Swatinem

`EXCEPTION_ACCESS_VIOLATION` is defined as `0xC0000005`, which overflows
an i32 and will turn negative, which causes processing problems later on.

2020-10-01 11:16 UTC, flub approved these changes

2020-10-01 14:55 UTC, jan-auer requested changes
Have you considered simply representing those as double?

There's one obvious problem with representing `uint32_t `: They are not interchangeable with `int32_t`. Now, instead of just checking for a numeric value, you always have to check for two possibilities:
- Is it an int32_t? Then do one thing.
- Is it a uint32_t? Then do another thing.

We could at least shim this in functions like `sentry_value_as_uint32` and then return a value if it fits, and vice versa. For example, if the value is a positive `int32_t`, still return the `uint32_t` counterpart. However, this may lead to strange behavior if suddenly an unexpected value lands in one of the fields.

Furthermore, the JSON parser does not support deserializing `uint32_t` yet. If you were to do a roundtrip, you'd deserialize as double. Any caller who depends on `as_uint32` would fail.

2020-10-01 14:55 UTC, jan-auer commented on src/sentry_value.c
> +        return sentry_value_as_uint32(value) > 0;
_nit_: Keep it consistent with the previous one.

```suggestion
        return sentry_value_as_uint32(value) != 0;
```

2020-10-05 13:49 UTC, Swatinem commented
superceded by #392

2020-10-05 13:49 UTC, closed without merging